ArtisanAlley/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('artworks.urls')),
    path('artists/', include('artists.urls')),
]

artists/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),

    path('', views.profiles, name="profiles"),
    path('profile/<uuid:pk>', views.artistProfile, name="artist-profile"),
    path('account/', views.userAccount, name="account"),

    path('edit-account/', views.editAccount, name="edit-account"),

    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path(
        'create-message/<str:pk>/', views.createMessage,
        name="create-message"),
]

artworks/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('' , views.artworks, name="artworks"),
    path('artwork/<str:pk>', views.artwork, name="artwork"),

    path(
        'create-artwork/', 
        views.createArtwork, 
        name="create-artwork"),

    path(
        'update-artwork/<str:pk>/',
        views.updateArtwork,
        name="update-artwork"
    ),

    path(
        'delete-artwork/<str:pk>/',
        views.deleteArtwork, name="delete-artwork"
    ),
]

artworks/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from . import choices
from artists.models import Profile

# Create your models here.


class Artworks(models.Model):
    """
    Stores a single artwork entry related to :model:`artists.Profile`
    and :model: 'artworks.Tag`.

    """

    profile_owner = models.ForeignKey(
        Profile, null=True, blank=True,
        on_delete=models.SET_NULL
    )
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = CloudinaryField('image', default='placeholder')
    listing_image1 = CloudinaryField('image', blank=True, null=True)
    listing_image2 = CloudinaryField('image', blank=True, null=True)
    listing_image3 = CloudinaryField('image', blank=True, null=True)
    price = models.IntegerField()
    town = models.CharField(max_length=100)
    county = models.CharField(max_length=100, choices=choices.COUNTIES)
    art_medium = models.CharField(max_length=50)
    tags = models.ManyToManyField('Tag', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True,
        editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']


class Tag(models.Model):
    """
    Stores a single tag
    """
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True,
        editable=False)

    def __str__(self):
        return self.name

artworks/forms.py
from django.forms import ModelForm, widgets
from django import forms
from cloudinary.forms import CloudinaryFileField
from .models import Artworks


class ArtworkForm(ModelForm):
    """
    The class defines Artwork form for create and edit
    artworks
    """
    featured_image = CloudinaryFileField()
    listing_image1 = CloudinaryFileField()
    listing_image2 = CloudinaryFileField()
    listing_image3 = CloudinaryFileField()

    class Meta:
        model = Artworks
        fields = [
            'title', 'description', 'featured_image',
            'listing_image1', 'listing_image2', 'listing_image3',
            'price', 'town', 'county', 'art_medium', 'tags'
        ]
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

artworks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from cloudinary.forms import cl_init_js_callbacks
from .models import Artworks
from .forms import ArtworkForm
from .utils import paginateArtworks

# Create your views here.


def artworks(request):
    """
    Renders the most recent artworks on the website and allows viewing
    Displays an individual instance of :model:`artworks.Artworks`
    and handles pagination
    """
    artworks = Artworks.objects.all()

    custom_range, artworks = paginateArtworks(request, artworks, 6)

    context = {'artworks': artworks, 'custom_range': custom_range}
    return render(request, 'artworks/artworks.html', context)


def artwork(request, pk):
    """
    The view handles display of details in a single artwork piece
    """
    artworkObj = Artworks.objects.get(id=pk)
    return render(
        request, 'artworks/single-artwork.html',
        {'artwork': artworkObj})


@login_required(login_url="login")
def createArtwork(request):
    """
    The view handles creation of new artwork via ArtworkForm
    """
    profile = request.user.profile
    form = ArtworkForm()

    if request.method == 'POST':
        form = ArtworkForm(request.POST, request.FILES)
        if form.is_valid():
            artwork = form.save(commit=False)
            artwork.profile_owner = profile
            artwork.save()
            messages.success(request, 'Artwork was created successfully!')
            return redirect('account')

    context = {'form': form}
    return render(request, 'artworks/artwork_form.html', context)


@login_required(login_url="login")
def updateArtwork(request, pk):
    """
    The view handles update of any artwork piece via Artwork form
    """
    profile = request.user.profile
    artwork = profile.artworks_set.get(id=pk)
    form = ArtworkForm(instance=artwork)

    if request.method == 'POST':
        form = ArtworkForm(request.POST, instance=artwork)
        if form.is_valid():
            form.save()
            messages.success(request, 'Artwork was updated successfully!')
            return redirect('account')

    context = {'form': form}
    return render(request, 'artworks/artwork_form.html', context)


@login_required(login_url="login")
def deleteArtwork(request, pk):
    """
    The view handles delete request of any artwork and confirm
    deletion using delete-artwork template
    """
    profile = request.user.profile
    artwork = profile.artworks_set.get(id=pk)
    if request.method == 'POST':
        artwork.delete()
        messages.success(request, 'Artwork was deleted successfully!')
        return redirect('account')
    context = {'object': artwork}
    return render(request, 'artworks/delete_artwork.html', context)

artworks/templates/artworks/artwork_form.html
{% extends 'main.html' %}
{% load cloudinary %}
{% load widget_tweaks %}
{% block content %}

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10 text-center my-5 p-4 form-container">
                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row justify-content-center">
                        <h1>Artwork Details</h1>
                        <div class="col-12 mt-3">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <!-- Title -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.title|attr:'required' class="form-control" %}
                                        <label for="id_title" class="form-label">Title: </label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    <!-- Art Medium -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.art_medium|attr:'required' class="form-control" %}
                                        <label for="id_art_medium" class="form-label">Art Medium: </label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>

                                    <!-- Town -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.town|attr:"pattern:^[A-Za-z\- ]+$"|attr:"title:Please enter valid town" class="form-control" placeholder=form.town.label %}
                                        <label for="id_town" class="form-label">Town: *</label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    <!-- County -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.county class="form-control" %}
                                        <label for="id_county" class="form-label">County: *</label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <!-- Price -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.price|attr:"max:1000000"|attr:"min:1"|attr:"title:Please enter amount between 1, 1000000" class="form-control" placeholder=form.price.label %}
                                        <label for="id_price" class="form-label">Price: *</label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Description -->
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group mb-4">
                                    <label for="id_description" class="form-label">Description:</label>
                                    {% render_field form.description|attr:"maxlength:2500" class="form-control" placeholder='Max 2500 characters' %}
                                    {% for error in field.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Tags -->
                        <div class="row align-items-start">
                            <div class="col-10">
                                <div class="form-group mb-4 py-3">
                                    <label for="id_tags" class="form-label">Tags:</label>
                                    {{ form.tags }}
                                    {% for error in form.tags.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Images -->
                        <div class="row">
                            <div class="col-12">
                                <h3>Images:</h3>
                                <div class="form-group mb-4">
                                    <label for="id_featured_image" class="form-label">Featured Image:</label>
                                    {% render_field form.featured_image class="form-control" %}
                                    {% for error in field.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>

                                <div class="form-group mb-4">
                                    <label for="id_listing_image1" class="form-label ">Additional Images:</label>
                                    {% render_field form.listing_image1 class="form-control" %}
                                    {% for error in field.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>

                                <div class="form-group mb-4">
                                    <label for="id_listing_image2" class="form-label sr-only">Additional
                                        Images:</label>
                                    {% render_field form.listing_image2 class="form-control" %}
                                    {% for error in field.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>

                                <div class="form-group mb-4">
                                    <label for="id_listing_image3" class="form-label sr-only">Additional
                                        Images:</label>
                                    {% render_field form.listing_image3 class="form-control" %}
                                    {% for error in field.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-secondary btn-lg">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

artworks/templates/artworks/artworks.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<!-- Hero Section-->
{% include 'partials/hero-section.html' %}

<section>
    <div class="container-fluid text-center mt-4 py-3">
        <div class="row">
            <div class="col">
                <h1>Welcome to Artisan Alley</h1>
            </div>
        </div>
        <div class="row justify-content-center py-3">
            <div class="col-8 mx-auto px-2">
                <p>
                    Welcome to Artisan Ireland, the ultimate directory celebrating the vibrant world of Irish
                    craftsmanship and
                    creativity! This platform is dedicated to showcasing the talent and passion of artisans from
                    every corner of
                    Ireland. Here, you can:
                </p>
                <p>
                    Discover skilled artists and unique creations that tell stories of Irish heritage and
                    ingenuity.<br>
                    Support local craftsmanship by connecting directly with artisans.<br>
                    Inspire your creativity by exploring the diverse arts and crafts that Ireland has to
                    offer.
                </p>
                <p>
                    Whether you're an artisan looking to showcase your work or a connoisseur seeking
                    inspiration, Artisan
                    Alley is here to bring you closer to the heart of Irish creativity. Together, let’s keep the
                    spirit of
                    artistry thriving! Feel free to dive in, explore, and make meaningful connections within our
                    vibrant
                    community
                </p>
                <p>
                    Welcome aboard, and thank you for being a part of this journey! 🌈🎭💚
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col justify-content-center">
                <h1>Artworks</h1>
            </div>
        </div>
        <div class="row mt-5 g-4 mx-5 justify-content-center">
            {% for artwork in artworks %}
            <!-- Card -->
            <div class="col-md-4">
                <a href=" {% url 'artwork' artwork.id %}" class="card-link">
                    <div class="card">

                        {% if "placeholder" in artwork.featured_image.url %}
                        <img src="{% static 'images/default-artwork.webp' %}" class="card-img-top artwork-image"
                            alt="placeholder photo">
                        {% else %}
                        <img src="{{ artwork.featured_image.url }}" class="card-img-top artwork-image"
                            alt="{{artwork.title}}">
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title text-truncate">{{artwork.title}}</h4>
                            <h5 class="card-subtitle mb-2 text-muted">By
                                {{artwork.profile_owner.name}}</h5>

                            <p> <i class="fas fa-map-marker-alt p-1"></i>{{artwork.town|capfirst}},
                                {{artwork.county|capfirst}}</p>
                            <h5><i class="fas fa-euro-sign p-1"></i>{{ artwork.price }}</h5>
                            <small><strong>Medium:</strong>{{artwork.art_medium}}</small>
                            <div class="row justify-content-center mt-3">
                                {% for tag in artwork.tags.all %}
                                <div class="col-3">
                                    <span class="badge text-bg-success p-2 ">
                                        <small>{{tag}}</small>
                                    </span>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    {% include 'pagination.html' with queryset=artworks custom_range=custom_range %}
</section>

{% endblock content %}

artworks/templates/artworks/delete_artwork.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% block content %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-4 mx-auto my-5 p-4 text-center form-container">
                <form method="POST" class="mt-3">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{object}}" ?</p>
                    <h5>This action cannot be undone!</h5>

                    <a href="{% url 'account' %}" class="btn btn-secondary mx-2">Go
                        Back</a>
                    <button type="submit" class="btn btn-secondary mx-2">Confirm</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

artworks/templates/artworks/single-artwork.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<section>
    <div class="container py-5 single-artwork-container">
        <div class="row">
            <!-- Artwork Carousel -->
            <div class="col-md-6">
                <div id="artworkCarousel" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            {% if "placeholder" in artwork.featured_image.url  %}
                            <img src="{% static 'images/default-artwork.webp' %}" class="card-img-top"
                                alt="placeholder photo">
                            {% else %}
                            <img src="{{ artwork.featured_image.url }}" class="card-img-top" alt="{{artwork.title}}">
                            {% endif %}
                        </div>
                        <div class="carousel-item">
                            {% if artwork.listing_image1.url %}
                            <img src="{{ artwork.listing_image1.url }}" alt="{{artwork.title}}">
                            {% endif %}
                        </div>
                        <div class="carousel-item">
                            {% if artwork.listing_image2.url %}
                            <img src="{{ artwork.listing_image2.url }}" alt="{{artwork.title}}">
                            {% endif %}
                        </div>
                        <div class="carousel-item">
                            {% if artwork.listing_image3.url %}
                            <img src="{{ artwork.listing_image3.url }}" alt="{{artwork.title}}">
                            {% endif %}
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#artworkCarousel"
                        data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#artworkCarousel"
                        data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>

            <!-- Artwork Details -->
            <div class="col-md-6">
                <h1>{{ artwork.title }}</h1>
                <p class="text-muted">{{ artwork.profile_owner.name }}</p>
                <h4><i class="fas fa-euro-sign p-1"></i>{{artwork.price}}</h4>
                <p><strong>Medium: </strong>{{ artwork.art_medium }} </p>
                <p><strong>Location: </strong> {{artwork.town|capfirst}}, {{artwork.county|capfirst}}</p>
                <div class="row my-3">
                    {% for tag in artwork.tags.all %}
                    <div class="col-2">
                        <span id="art-tag" class="badge text-bg-success p-2 ">
                            <small>{{tag}}</small>
                        </span>
                    </div>
                    {% endfor %}
                </div>
                <p>Description: {{ artwork.description }}</p>
                {% if request.user.profile.id != artwork.profile_owner.id %}
                <a href="{% url 'artist-profile' artwork.profile_owner.id %}" class="btn btn-secondary mt-3">Contact
                    Artist</a>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock content %}
{% block script %}
<script src="{% static 'js/artwork.js' %}"></script>
{% endblock script %}