ArtisanAlley/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('artworks.urls')),
    path('artists/', include('artists.urls')),
]

artists/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),

    path('', views.profiles, name="profiles"),
    path('profile/<uuid:pk>', views.artistProfile, name="artist-profile"),
    path('account/', views.userAccount, name="account"),

    path('edit-account/', views.editAccount, name="edit-account"),

    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path(
        'create-message/<str:pk>/', views.createMessage,
        name="create-message"),
]

artists/models.py
from django.contrib.auth.models import User
from django.db import models
from cloudinary.models import CloudinaryField
import uuid

# Create your models here.


class Profile(models.Model):
    """
    Stores artist profile informtion related to :model: `auth.User`
    """

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = CloudinaryField('image')
    social_facebook = models.CharField(max_length=200, blank=True, null=True)
    social_instagram = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
        )

    def __str__(self):
        return str(self.username)


class Message(models.Model):
    """
    Stores messages related to :model: `artists.Profile`
    """
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="receiver_messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, blank=True, null=True)
    subject = models.CharField(max_length=200, blank=True, null=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']

artworks/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from . import choices
from artists.models import Profile

# Create your models here.


class Artworks(models.Model):
    """
    Stores a single artwork entry related to :model:`artists.Profile`
    and :model: 'artworks.Tag`.

    """

    profile_owner = models.ForeignKey(
        Profile, null=True, blank=True,
        on_delete=models.SET_NULL
    )
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = CloudinaryField('image', default='placeholder')
    listing_image1 = CloudinaryField('image', blank=True, null=True)
    listing_image2 = CloudinaryField('image', blank=True, null=True)
    listing_image3 = CloudinaryField('image', blank=True, null=True)
    price = models.IntegerField()
    town = models.CharField(max_length=100)
    county = models.CharField(max_length=100, choices=choices.COUNTIES)
    art_medium = models.CharField(max_length=50)
    tags = models.ManyToManyField('Tag', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True,
        editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']


class Tag(models.Model):
    """
    Stores a single tag
    """
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True,
        editable=False)

    def __str__(self):
        return self.name

artists/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from cloudinary.forms import CloudinaryFileField
from django.forms import ModelForm
from .models import Profile, Message


class CustomUserCreationForm(UserCreationForm):
    """
    The class defines custom user creation form on user registration
    """
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',
        }


class ProfileForm(ModelForm):
    """
    The class defines Profile form that reflects on artist
    account

    """
    profile_image = CloudinaryFileField()

    class Meta:
        model = Profile
        fields = [
            'name', 'email', 'username', 'location', 'bio',
            'short_intro', 'profile_image', 'social_instagram',
            'social_website', 'social_facebook'
        ]


class MessageForm(ModelForm):
    """
    The class defines fields for sending a message
    to an artist

    """
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

artists/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import Profile
from .forms import CustomUserCreationForm, ProfileForm, MessageForm
from .utils import paginateProfiles


# Create your views here.

def loginUser(request):
    """
    The view handles login request using
    login template
    """
    page = 'login'
    context = {'page': page}

    if request.user.is_authenticated:
        return redirect('artworks')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You are successfully logged in!')
            return redirect('artworks')
        else:
            messages.error(request, 'Username OR password is incorrect')

    return render(request, 'artists/login_register.html')


def logoutUser(request):
    """
    The view logs user out and displays
    info message

    """
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('login')


def registerUser(request):
    """
    The view handles registration request using
    CustomUserCreation form
    """
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            messages.success(request, 'User account was created!')

            login(request, user)
            return redirect('edit-account')

        else:
            messages.error(
                request, 'An error has occurred during registration')

    context = {'page': page, 'form': form}
    return render(request, 'artists/login_register.html', context)


def profiles(request):
    """
    The view displays list of all registered artists
    on the platform and allows search via name and location

    """
    search_query = ''

    if request.GET.get('search_query'):
        search_query = request.GET.get('search_query')

    profiles = Profile.objects.filter(
        Q(name__icontains=search_query) | Q(location__icontains=search_query))

    custom_range, profiles = paginateProfiles(request, profiles, 3)

    context = {
        'profiles': profiles, 'search_query': search_query,
        'custom_range': custom_range}
    return render(request, 'artists/profiles.html', context)


def artistProfile(request, pk):
    """
    The view handles individual artist profile

    """
    profile = Profile.objects.get(id=pk)
    context = {'profile': profile}
    return render(request, 'artists/artist_profile.html', context)


@login_required(login_url='login')
def userAccount(request):
    """
    The view displays artist profile info and display artworks
    created by the artists
    """
    profile = request.user.profile
    artworks = profile.artworks_set.all()

    context = {'profile': profile, 'artworks': artworks}
    return render(request, 'artists/account.html', context)


@login_required(login_url='login')
def editAccount(request):
    """
    The view handles editing user account
    """
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your account details are succefssfully edited!')

            return redirect('account')

    context = {'form': form}
    return render(request, 'artists/profile_form.html', context)


@login_required(login_url='login')
def inbox(request):
    """
    The view displays message inbox and shows
    messages sent by registered artists or site visitors

    """
    profile = request.user.profile
    messageRequests = profile.receiver_messages.all()
    unreadCount = messageRequests.filter(is_read=False).count()

    context = {'messageRequests': messageRequests, 'unreadCount': unreadCount}
    return render(request, 'artists/inbox.html', context)


@login_required(login_url='login')
def viewMessage(request, pk):
    """
    The view shows message box displaying message details
    sent by sender

    """
    profile = request.user.profile
    message = profile.receiver_messages.get(id=pk)

    if message.is_read is False:
        message.is_read = True
        message.save()

    context = {'message': message}
    return render(request, 'artists/message.html', context)


def createMessage(request, pk):
    """
    The view allows creation of new message to send to an artist.
    Based on registered or unregisted user, the form displays different fields

    """

    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profile
    except AttributeError:
        sender = None

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()

            messages.success(request, 'Your message was succefssfully sent!')
            return redirect('artist-profile', pk=recipient.id)

    context = {'recipient': recipient, 'form': form}
    return render(request, 'artists/message_form.html', context)

artists/templates/artists/account.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

<!-- Profile Section -->
<section>
    <div class="container py-5">
        <div class="row mb-4">
            <div class="col-md-4">
                <img src="{{profile.profile_image.url}}" class="img-fluid rounded"
                    alt="Artist {{ profile.name }}Profile Picture">
            </div>
            <div class="col-md-8">
                <h1>{{ profile.name }}</h1>
                <p class="text-muted">Location: {{ profile.location }}</p>
                <p>{{profile.short_intro}}</p>
                <p>{{profile.bio}}</p>
                <p><strong>Email:</strong>{{ profile.email }}</p>
                <div class="artist-social">
                    {% if profile.social_facebook %}
                    <a href="{{profile.social_facebook}}" class="mx-1" target="_blank"><i
                            class="fab fa-facebook"></i></a>
                    {% endif %}

                    {% if profile.social_website %}
                    <a href="{{profile.social_website}}" class="mx-1" target="_blank"><i class="fas fa-globe"></i></a>
                    {% endif %}

                    {% if profile.social_instagram %}
                    <a href="{{profile.social_instagram}}" class="mx-1" target="_blank"><i
                            class="fab fa-instagram"></i></a>
                    {% endif %}

                </div>
                <div class="mt-3">
                    <a href="{% url 'edit-account' %}" class="btn btn-primary">Edit Account</a>
                </div>
            </div>
        </div>

        <!-- Artworks Section -->
        <h2>Artworks</h2>
        <div class="row g-4">
            <!-- Artwork 1 -->
            {% for artwork in artworks %}
            <div class="col-md-4">
                <div class="card h-100">
                    <a href="{% url 'artwork' artwork.id %}">
                        <img src="{{ artwork.featured_image.url }}" class="artwork-thumbnail" alt="artwork thumbnail">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ artwork.title }}</h5>
                        <p class="card-text">{{ artwork.description|slice:"150" }}</p>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'update-artwork' artwork.id %}" class="btn btn-primary"><i
                                    class="far fa-edit"></i>
                                Edit</a>
                            <a href="{% url 'delete-artwork' artwork.id %}" class="btn btn-danger"><i
                                    class="fas fa-trash-alt"></i>
                                Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

artists/templates/artists/artist_profile.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<section>
    <div class="container py-5">
        <div class="row mb-4">
            <div class="col-md-4">
                <img src="{{profile.profile_image.url}}" class="img-fluid rounded"
                    alt="Artist {{ profile.name }}Profile Picture">
            </div>
            <div class="col-md-8">
                <h1>{{ profile.name }}</h1>
                <p class="text-muted">Location: {{ profile.location }}</p>
                <p>{{profile.short_intro}}</p>
                <p>{{profile.bio}}</p>
                <p><strong>Email: </strong>{{ profile.email }}</p>
                <div class="artist-social">
                    {% if profile.social_facebook %}
                    <a href="{{profile.social_facebook}}" class="mx-1" target="_blank"><i
                            class="fab fa-facebook"></i></a>
                    {% endif %}

                    {% if profile.social_website %}
                    <a href="{{profile.social_website}}" class="mx-1" target="_blank"><i class="fas fa-globe"></i></a>
                    {% endif %}

                    {% if profile.social_instagram %}
                    <a href="{{profile.social_instagram}}" class="mx-1" target="_blank"><i
                            class="fab fa-instagram"></i></a>
                    {% endif %}

                </div>
                {% if request.user.profile.id != profile.id %}
                <a href="{% url 'create-message' profile.id %}" class="btn btn-secondary mt-4 text-decoration-none">Send
                    Message</a>
                {% endif %}
            </div>
        </div>

        <!-- Artworks Section -->
        <h2>Artworks</h2>
        <div class="row g-4">
            {% if profile.artworks_set.all %}
            {% for artwork in profile.artworks_set.all %}
            <div class="col-md-4">
                <div class="card h-100">
                    <a href="{% url 'artwork' artwork.id %}">
                        {% if "placeholder" in artwork.featured_image.url  %}
                        <img src="{% static 'images/default-artwork.webp' %}" class="artwork-thumbnail"
                            alt="placeholder photo">
                        {% else %}
                        <img src="{{ artwork.featured_image.url }}" class="artwork-thumbnail"
                            alt="{{artwork.title}} Image">
                        {% endif %}
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ artwork.title }}</h5>
                        <p class="card-text">{{ artwork.description }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-6">
                <p>You have not added any artworks.</p>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

artists/templates/artists/inbox.html
{% extends 'main.html' %}

{% block content %}

<section>
    <div class="container py-5 inbox">
        <div class="inbox-header d-flex justify-content-between align-items-center mb-4">
            <h3>New Messages(<span>{{ unreadCount }}</span>)</h3>
        </div>

        <!-- Message List -->
        <ul class="messages">
            {% for message in messageRequests %}
            {% if message.is_read == False %}
            <li class="message message-unread">
                {% else %}
            <li class="message">
                {% endif %}
                <a href="{% url 'message' message.id %}" class="text-decoration-none">
                    <span class="message-author">{{message.name}}</span>
                    <span class="message-subject">{{message.subject}}</span>
                    <span class="message-date">{{message.created}}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>

</section>
{% endblock %}

artists/templates/artists/message.html
{% extends 'main.html' %}

{% block content %}

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-4 mx-auto my-5 p-4 text-center message-box">

                <div class="message text-start">
                    <a class="text-decoration-none" href="{% url 'inbox' %}">Back</a>
                    <h2 class="message-subject my-2">{{message.subject}}</h4>
                        {% if message.sender %}
                        <a href="{% url 'artist-profile' message.sender.id  %}"
                            class="message-author text-decoration-none">{{message.name}}</a>
                        {% else %}
                        <p class="message-author">{{message.name}}</p>
                        {% endif %}
                        <p class="message-date text-start">{{message.created}}</p>
                        <div class="message-body text-start">{{message.body|linebreaksbr}}</div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

artists/templates/artists/message_form.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% block content %}


<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 my-5 p-4 form-container">
                <a class="text-decoration-none btn btn-secondary"
                    href="{% url 'artist-profile' recipient.id %}">Back</a>
                <h3 class="text-center">Message</h3>
                <form method="POST" class="mt-3">
                    {% csrf_token %}
                    {% if request.user.is_authenticated == False %}
                    <div class="row">
                        <div class="col-10">
                            <div class="form-floating mb-4">
                                {% render_field form.name|attr:'required' class="form-control" %}
                                <label for="id_name" class="form-label">Name: </label>
                                {% for error in field.errors %}
                                <span class="text-danger">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-10">
                            <div class="form-floating mb-4">
                                {% render_field form.email|attr:'required' class="form-control" %}
                                <label for="id_email" class="form-label">Email: </label>
                                {% for error in field.errors %}
                                <span class="text-danger">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    <div class="row">
                        <div class="col-10">
                            <div class="form-floating mb-4">
                                {% render_field form.subject|attr:'required' class="form-control" %}
                                <label for="id_subject" class="form-label">Subject: </label>
                                {% for error in field.errors %}
                                <span class="text-danger">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-10">
                            <div class="form-group mb-4">
                                <label for="id_body" class="form-label">Body:</label>
                                {% render_field form.body|attr:"maxlength:2500" class="form-control" placeholder='Max 2500 characters' %}

                                {% for error in field.errors %}
                                <span class="text-danger">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-lg btn-secondary">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>



{% endblock content %}

artists/templates/artists/profile_form.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% block content %}

<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-10 text-center my-5 p-4 form-container">
                <form action="{% url 'edit-account' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row justify-content-center">
                        <h1>Update Account</h1>
                        <div class="col-12 mt-3">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <!-- Name -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.name|attr:'required' class="form-control" %}
                                        <label for="id_name" class="form-label">Name: </label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    <!-- Email -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.email|attr:'required' class="form-control" %}
                                        <label for="id_email" class="form-label">Email: </label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>

                                    <!-- Location -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.location|attr:"pattern:^[A-Za-z\- ]+$"|attr:"title:Please enter valid location" class="form-control" placeholder=form.location.label %}
                                        <label for="id_location" class="form-label">Location: </label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    <!-- Username -->
                                    <div class="form-floating mb-4">
                                        {% render_field form.username class="form-control" %}
                                        <label for="id_username" class="form-label">Username: </label>
                                        {% for error in field.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Short Intro -->
                        <div class="row">
                            <div class="col-12">
                                <div class="form-floating mb-4">
                                    {% render_field form.short_intro class="form-control" %}
                                    <label for="id_short_intro" class="form-label">Short Intro:</label>
                                    {% for error in field.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Bio -->
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group mb-4">
                                    <label for="id_bio" class="form-label">Bio:</label>
                                    {% render_field form.bio|attr:"maxlength:2500" class="form-control" placeholder='Max 2500 characters' %}
                                    {% for error in field.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Images -->
                        <div class="row">
                            <div class="col-12">
                                <h3>Profile Image:</h3>
                                <div class="form-group mb-4">
                                    <label for="id_profile_image" class="form-label">Profile Image:</label>
                                    {% render_field form.profile_image class="form-control" %}
                                    {% for error in field.errors %}
                                    <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <!-- Social Channels -->
                        <div class="row">
                            <div class="col-12">
                                <div class="row">
                                    <div class="col-4">
                                        <!-- Social Facebook -->
                                        <div class="form-floating mb-4">
                                            {% render_field form.social_facebook class="form-control" %}
                                            <label for="id_social_facebook" class="form-label">Facebook:
                                            </label>
                                            {% for error in field.errors %}
                                            <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <!-- Social Website -->
                                        <div class="form-floating mb-4">
                                            {% render_field form.social_website class="form-control" %}
                                            <label for="id_social_website" class="form-label">Website:
                                            </label>
                                            {% for error in field.errors %}
                                            <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <!-- Social Instagram -->
                                        <div class="form-floating mb-4">
                                            {% render_field form.social_instagram class="form-control" %}
                                            <label for="id_social_instagram" class="form-label">Instagram:
                                            </label>
                                            {% for error in field.errors %}
                                            <span class="text-danger">{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary my-3 px-3">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}